# Generated by Django 2.2.7 on 2019-12-17 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='avatar',
            field=models.CharField(default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='person',
            name='hobby',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.Category'),
        ),
        migrations.AddField(
            model_name='person',
            name='personality',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.Category'),
        ),
        migrations.AddField(
            model_name='person',
            name='way_of_life',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.Category'),
        ),
        migrations.AlterField(
            model_name='person',
            name='tags',
            field=models.ManyToManyField(related_name='Persons', to='app.Tag'),
        ),
    ]
