# Generated by Django 2.2.7 on 2019-12-17 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191217_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='hobby',
            field=models.ForeignKey(default=27, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.Tag'),
        ),
        migrations.AlterField(
            model_name='person',
            name='personality',
            field=models.ForeignKey(default=27, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.Tag'),
        ),
        migrations.AlterField(
            model_name='person',
            name='way_of_life',
            field=models.ForeignKey(default=27, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.Tag'),
        ),
    ]
