# Generated by Django 2.2.7 on 2020-01-31 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_visitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
                ('message', models.CharField(default='None', max_length=1000)),
                ('receiver', models.ForeignKey(default=27, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='app.Person')),
                ('sender', models.ForeignKey(default=27, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='app.Person')),
            ],
        ),
    ]
